### ISSUE TITLE
对UniCATS训练数据的问题

### ISSUE THREAD

**Issue by awei669** [cantabile-kwok/UniCATS-CTX-text2vec#12]
作者您好，这篇工作可以将语音续写和编辑用一个模型实现，并且实现speaker-zero shot。工作十分有趣，感谢开源代码以供学习。

我对语音生成领域不是很熟悉，以下是我对UniCATS的一些理解：

在tex2vec模块当中，context-vq-diffusion的目的是给定完整text，根据上下文语音token预测续写/编辑部分对应的语音token，而预训练的vq-wav2vec则类比于vq-diffusion中的预训练vq-gan部分，用于从语音数据中提取特征token。这样输入任意的text（context + continuation），经过tex2vec模块即可预测具有上下文信息的语音特征，随后再用vec2wav模块将完整的语音token转换为连续的语音（并基于context speech将作者身份信息加入，从而可以实现zero-shot）。

我有一个问题：从文本角度来看语音续写或者编辑应该是以word为最小单位进行的，而语音数据貌似是以帧长等时间步来区分，它们之间需要对应起来么。例如编辑一行text中的某个单词，tex2vec模块用于根据这个单词的上下文语音预测对应的语音token，这是否意味训练和测试数据着需要word-level的语音标注？

**Comment by cantabile-kwok** [comment]
感谢您对我们工作的关注！

这个问题答案为”是的“。实际上，一般语音合成的输入单元是”音素“（phoneme），即发音的基本单位，一个词由若干音素组成，汉语中类似于拼音。所以我们在训练模型的时候实际上是预先得到了每个音素对应的语音帧级别对齐关系。获得这一步对齐关系是专门用一个forced alignment（强制对齐）工具得到的，即给定一条语音和对应的音素序列，把每个音素无重复、无遗漏地对上语音中的某几帧。

在测试时也是一样的，如果要进行语音编辑的话，就必须要知道要编辑的部分在语音中对应的是哪一段，这一步也是通过音素上的对齐来知道的。

**Comment by awei669** [comment]
明白了，这样做是符合常理的，非常感谢您的及时回复。
