### ISSUE TITLE
Hardware specs

### ISSUE THREAD

**Issue by georgealexandruvlad** [cantabile-kwok/UniCATS-CTX-text2vec#5]
Hi! 

First of all, congrats on the impressive work and thank you for taking the time to make it available on GitHub.

I have read the paper and I couldn't find any mention on the hardware setup for training. Any info about the hardware used for training and expected training times would be very much appreciated.
I am currently trying a 4GPU setup with 16GB of VRAM per node and training with default configuration seems to raise OOM. So I was wondering what hardware configuration would be adequate.

Thanks!

**Comment by danablend** [comment]
24 GB vRAM setup worked fine for me. NVIDIA A10G, specifically. I could also run both training and inference just fine on my 4 GB laptop GPU.

Perhaps something else is causing you trouble, other than hardware?

**Comment by georgealexandruvlad** [comment]
Interesting. Then I'll have another look at what is actually causing the OOM now that the GPU memory constraint has been ruled out. Thanks!

**Comment by cantabile-kwok** [comment]
For your information, the training in the paper was done by V100 GPU with 32GB VRAM, so probably one needs to decrease the batch size if OOM occurs on GPUs with less VRAMs.
